### ISSUE TITLE
docs - multi-datasource config inconsistency

### ISSUE THREAD

**Issue by zyro23** [grails/grails-data-mapping#2015]
configuring two dataSources,

* https://github.com/grails/gorm-hibernate5/blob/v6.0.8/docs/src/docs/asciidoc/multipleDataSources/configuration.adoc says
```yml
dataSource:
    # primary dataSource config ("dataSource")
dataSources:
    secondary:
        # secondary dataSource config ("dataSource_secondary")
```
is the correct format while
* http://docs.grails.org/3.2.6/guide/conf.html#multipleDatasources
* https://github.com/grails/grails3-functional-tests/blob/3.2.x/datasources/grails-app/conf/application.yml
* https://github.com/grails/gorm-hibernate5/blob/v6.0.8/grails-datastore-gorm-hibernate5/src/main/groovy/grails/orm/bootstrap/HibernateDatastoreSpringInitializer.groovy#L93

indicate that the correct format is:
```yml
dataSources:
    dataSource:
        # primary dataSource config ("dataSource")
    secondary:
        # secondary dataSource config ("dataSource_secondary")
```
