### ISSUE TITLE
Grails multiple datasource, not working when trying to save a new Instance into selected datasource

### ISSUE THREAD

**Issue by johngamarra** [grails/grails-data-mapping#668]
I'm having this issue with a simple configuration when working with multiple datasources and I'm trying to save a new instance into a specific datasource

my datasources:

```
dataSources:
    dataSource:
        pooled: true
        jmxExport: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: Choice2016
    dominio1:
        pooled: true
        jmxExport: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: Choice2016
    dominio2:
        pooled: true
        jmxExport: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: Choice2016
```

my domain

```
class Nxtt_reports {

    Boolean favorite

    static hasMany = [nxtt_report_histories: Nxtt_report_history, nxtt_user_reports: Nxtt_user_reports, nxtt_report_snapshots: Nxtt_report_snapshot]

    static constraints = {

    }

    static mapping = {
        datasource 'ALL'
    }

}
```

when I do this,

```
        def nxtt = Nxtt_reports.class
        println(nxtt.dominio1.list())
```

I can list data in the domain I want, but if I do this

```
        def nxtt = Nxtt_reports.class.newInstance()
        nxtt.favorite = 0
        nxtt.dominio2.save()
```

I'm getting this

No such property: dominio2 for class: nexttreport.server.Nxtt_reports. Stacktrace follows:
groovy.lang.MissingPropertyException: No such property: dominio2 for class: nexttreport.server.Nxtt_reports

using:

| Grails Version: 3.1.1
| Groovy Version: 2.4.5
| JVM Version: 1.8.0_65
