### ISSUE TITLE
Cannot use Mogodb and Hibernate combined with version 4.0 and Grails 3.0.1

### ISSUE THREAD

**Issue by zee007pk** [grails/grails-data-mapping#68]
Using Grails 3.0.1. Add "compile 'org.grails.plugins:mongodb:4.0.0'" in build.grade. Create a domain class class without "static mapWith='mongo'".  Provide a dataSource for hibernate. Save a valid instance of this domain class in BootStrap. This instance would be saved in mongo. 
Remove mongo plugin, then save the instance. Now it will be saved in configured hibernate database.

Code:
Domain HibernateDomain.groovy 
```
class HibernateDomain {
    String name
    static constraints = {
    }
}
```
Domain MongoDomain.groovy 
```
class MongoDomain {
    static mapWith = "mongo"
    String name
    static constraints = {
    }
}
```
Hibernate Datasource (application.yml)
```
dataSource:
        driverClassName: org.h2.Driver
        username: sa
        password:
        dbCreate: create-drop
        url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
```
Mongodb settings (application.yml):

```
grails:
    mongodb:
        connectionString: mongodb://localhost/hibernate4-mongo4
```
Bootstrap.groovy
```
class BootStrap {

    def init = { servletContext ->
        HibernateDomain hibernateDomain = new HibernateDomain(name:"hibernate1")
        hibernateDomain.save()
        MongoDomain mongoDomain = new MongoDomain(name:"mongo1")
        mongoDomain.save()
        hibernateDomain.withSession { s->
            println "Session class for hibernateDomain is: ${s.class.name}" //Output: Session class for hibernateDomain is: org.grails.datastore.mapping.mongo.MongoSession
        }
    }
    def destroy = {
    }
}

```
Download example project from here
https://drive.google.com/file/d/0B8f07nE2xFSyZ0lwT2Q4aFVjUkU/view?usp=sharing
