### ISSUE TITLE
Dcoument how to define TenantResolver as a spring bean

### ISSUE THREAD

**Issue by snimavat** [grails/grails-data-mapping#747]
Gorm multitenancy docs says

>  if you are using Grails or Spring Boot then the TenantResolver can also be specified as a Spring bean and it will automatically be injected, this allows you to use dependency injection to configure the dependencies of the resolver.

However it is unclear how to do the same.

The multitenancy settings needs the class name and not the bean name (as per example)

```
grails:
    gorm:
        multiTenancy:
            mode: DATABASE
            tenantResolverClass: org.grails.datastore.mapping.multitenancy.web.SubDomainTenantResolver
```

And looks like it just [instantiates](https://github.com/grails/grails-data-mapping/blob/2ca7c5ad9d8320915cf4e4b8e46cb549ece71ca3/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/multitenancy/MultiTenancySettings.groovy#L35) the class

So, instead of specifying the classname, if i wanted to specify a spring bean name for tenant resolver, how would i do that ?

@graemerocher
