### ISSUE TITLE
3.2.0.M2-  Another unnamed CacheManager already exists in the same VM

### ISSUE THREAD

**Issue by snimavat** [grails/grails-data-mapping#749]
Brand new 3.2.0.M2 project with multiple datasources fails with error 

```
et.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
```

Shouldnt it work outof the box without needing to change the factory_class or any thing ? Multipledatasource docs doesnt seem to provide any clue on the potenrial error or the right solution.

The default generated hibernate config is this

```
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
```

Grails 2.5.5 came with cache.region.factory_class = 'org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory' as default

Though removing thie hibernate config block completely like in ur multi tenant [example](https://github.com/grails/gorm-hibernate5/blob/master/examples/grails31-database-per-tenant/grails-app/conf/application.yml) works

Which one would be the right choice to use when using multiple datasources, or whats the right solution to this problem.

@graemerocher
