### ISSUE TITLE
autoTimestamp not working when setting mongo client connection to domain objects

### ISSUE THREAD

**Issue by dshrestha** [grails/grails-data-mapping#851]
In my application I have multiple mogoclient connection configured in my application.yml

```
    mongodb:
      url: '${CONNECTION_URL_0}'
      connections:
        analytics:
          url: '${CONNECTION_URL_0}'
        reporting:
          url: '${CONNECTION_URL_1}'

```

when I set autoTimestamp to true on a domain object and save it, its not adding the dateCreated/lastUpdated to databse record. I found out that the issue only happens when I define connection parameter in the domain mapping, if I don't define it things do work. Eg:

```
class Labels {

    ObjectId id
    String label
    Long createdBy
    Long lastUpdatedBy
    Date dateCreated
    Date lastUpdated

    static mapping = {
        connection "analytics"//IF I COMMENT THIS LINE THEN DATES ARE ADDED
        collection "labels"

        id attr: "_id"
        autoTimestamp true
    }
   
}
```

I am using 'org.grails.plugins:mongodb:6.0.5' and grails 3.2.4 . I tried adding beforeInsert hook but that was not getting executed either. Any advice would be highly appreciated.

Thanks.
