### ISSUE TITLE
grails 3.0.17, two datasources (one readonly datasource) No Session found Exception

### ISSUE THREAD

**Issue by kevinclcn** [grails/grails-data-mapping#893]
My datasource configuration looks something like below:

```yml
dataSources:
    dataSource: &baseDataSource
        pooled: true
        jmxExport: true
        driverClassName: com.mysql.jdbc.Driver
        properties:
            jmxEnabled: true
            initialSize: 10
            maxActive: 100
            minIdle: 10
            maxIdle: 50
            maxWait: 10000
            maxAge: 600000
            timeBetweenEvictionRunsMillis: 5000
            minEvictableIdleTimeMillis: 60000
            validationQuery: SELECT 1
            validationQueryTimeout: 3
            validationInterval: 15000
            testOnBorrow: true
            testWhileIdle: true
            testOnReturn: false
            jdbcInterceptors: ConnectionState
            defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    lookup:
        <<: *baseDataSource
        readOnly: true
        transactional: false

```

I have a domain class `Task` with constraints:

```groovy
class ImportTask {
	String status = "initial"  //processing, finish
	int blocks
	String completeBlocks
	int allCount
	int successCount
	int failedCount
	String taskType 
	int attachmentId
	String failReason
	Date dateCreated
	Date lastUpdated
	
	static constraints = {
		completeBlocks (size: 0..4096)
		taskDef (size: 0..4096)	
	}
}
```

In the import task job, I my code is something like this:

```groovy
ImportTask.withTransaction {
   try {
          def importTask = ImportTask.get(1)
          if (importTask) {
                importTask.status = 'processing'
                importTask.save(flush: true)
         }

   } catch (Exception e) {
      log.error "=== failed to start import task ===", e
  } 
}
```

`org.hibernate.HibernateException: No Session found for current thread` would be thrown. 

After some debugging, I found the `HibernateDomainClassValidator` refs to the `lookup` datasource sessionFactory. Is it a bug? How can I workaround it?
